import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import React from "react";
import MainNav from "@/components/nav/main-nav";
import Footer from "@/components/nav/footer";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Investwell",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <div className={"flex min-h-screen flex-col justify-between"}>
          <MainNav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
